module.exports = {
  apps: [
    {
      name:            "gateway",
      script:          "./gateway/src/index.ts",
      interpreter:     "/home/darthvader/zapflow2/module-telegram/node_modules/.bin/tsx",
      env_file:        ".env",
      env:             { PORT: 4000 },
      autorestart:     true,
      max_restarts:    10,
      restart_delay:   3000,
      watch:           false,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name:               "module-whatsapp",
      script:             "./module-whatsapp/src/index.ts",
      interpreter:        "/home/darthvader/zapflow2/module-telegram/node_modules/.bin/tsx",
      env_file:           ".env",
      env:                { PORT: 4001 },
      autorestart:        true,
      max_restarts:       15,
      restart_delay:      5000,
      max_memory_restart: "600M",
      watch:              false,
    },
    {
      name:            "module-email",
      script:          "./module-email/src/index.ts",
      interpreter:     "/home/darthvader/zapflow2/module-telegram/node_modules/.bin/tsx",
      env_file:        ".env",
      env:             { PORT: 4002 },
      autorestart:     true,
      max_restarts:    10,
      restart_delay:   3000,
      watch:           false,
    },
    {
      // ── module-telegram — Python + Telethon ──────────────────────────
      // interpreter: "python3" (PM2 vai usar o python3 do PATH)
      // Se usar virtualenv: interpreter: "./module-telegram-python/venv/bin/python"
      name:            "module-telegram",
      script:          "src/main.py",
      cwd:             "./module-telegram-python",
      interpreter:     "python3",
      // Para usar virtualenv (recomendado em produção), descomente:
      // interpreter:  "./module-telegram-python/venv/bin/python",
      env_file:        ".env",
      env:             { TELEGRAM_PORT: 4003 },
      autorestart:     true,
      max_restarts:    10,
      restart_delay:   3000,
      watch:           false,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name:            "module-ai",
      script:          "./module-ai/src/index.ts",
      interpreter:     "/home/darthvader/zapflow2/module-telegram/node_modules/.bin/tsx",
      env_file:        ".env",
      env:             { PORT: 4004 },
      instances:       1,
      autorestart:     true,
      max_restarts:    10,
      restart_delay:   3000,
      watch:           false,
    },
  ],
}
