module.exports = {
  apps: [
    {
      name:            "gateway",
      script:          "./gateway/src/index.ts",
      interpreter:     "./node_modules/.bin/tsx",
      env_file:        ".env",
      env:             { PORT: 4000 },
      autorestart:     true,
      max_restarts:    10,
      restart_delay:   3000,
      watch:           false,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name:               "module-whatsapp",
      script:             "./module-whatsapp/src/index.ts",
      interpreter:        "./node_modules/.bin/tsx",
      env_file:           ".env",
      env:                { PORT: 4001 },
      autorestart:        true,
      max_restarts:       15,
      restart_delay:      5000,
      max_memory_restart: "600M",
      watch:              false,
    },
    {
      name:            "module-email",
      script:          "./module-email/src/index.ts",
      interpreter:     "./node_modules/.bin/tsx",
      env_file:        ".env",
      env:             { PORT: 4002 },
      autorestart:     true,
      max_restarts:    10,
      restart_delay:   3000,
      watch:           false,
    },
    {
      // ── module-telegram — Python + Telethon (conta real, NÃO bot) ──────
      // O module-telegram TypeScript (bot) foi REMOVIDO propositalmente
      // para evitar conflito de porta 4003 e fila Redis "zf-telegram"
      name:            "module-telegram",
      script:          "src/main.py",
      cwd:             "./module-telegram-python",
      // IMPORTANTE: use o python do virtualenv (criado pelo setup_telegram.sh)
      interpreter:     "./module-telegram-python/venv/bin/python",
      // Fallback sem venv: interpreter: "python3",
      env_file:        ".env",
      env:             { TELEGRAM_PORT: 4003, PYTHONUNBUFFERED: '1' },
      autorestart:     true,
      max_restarts:    10,
      restart_delay:   3000,
      watch:           false,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name:            "module-ai",
      script:          "./module-ai/src/index.ts",
      interpreter:     "./node_modules/.bin/tsx",
      env_file:        ".env",
      env:             { PORT: 4004 },
      instances:       1,
      autorestart:     true,
      max_restarts:    10,
      restart_delay:   3000,
      watch:           false,
    },
  ],
}